### ISSUE TITLE
Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by pedrocruzio** [vizorvr/vizor#1985]
I tried installing a local instance by following the instructions: 

` $ npm install && npm install -g gulp`
` $ brew install graphicsmagick`
` $ gulp`

But I get the following error:

```module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/Pedro/Documents/Programming Projects/vizor/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)```

**Comment by esaruoho** [comment]
@pedrocruzio  have you tried installing gridfs?
