### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by tobischulz** [vizorvr/vizor#2008]
Hello,

got that syntax errors. Am i using a wrong version of something?

`root@vizorvr:/home/vizor/vizor# npm test

> Vizor@0.16.3 test /home/vizor/vizor
> npm run gulp-engine && npm run test:browser && npm run test:server

> Vizor@0.16.3 gulp-engine /home/vizor/vizor
> node ./node_modules/gulp/bin/gulp js:engine

^C
root@vizorvr:/home/vizor/vizor#
root@vizorvr:/home/vizor/vizor#
root@vizorvr:/home/vizor/vizor# gulp
/home/vizor/vizor/tools/pushPlayerToGrid.js:12
	let CloudFileSystemImpl
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vizor/vizor/gulpfile.js:10:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

Nodejs: v4.8.3
Gulp CLI version 3.9.0
Gulp Local version 3.9.0

**Comment by tobischulz** [comment]
I guess its fixed by:

`
sudo npm install -g npm
sudo npm install -g n
sudo n stable`
