### ISSUE TITLE
ReqlOpFailedError: Database `vizor` does not exist in...

### ISSUE THREAD

**Issue by apaatsio** [vizorvr/vizor#651]
I'm getting an error when trying to run the app locally.

Preconditions:
mongo and rethinkdb are installed and running. All tests pass.

Steps:
1. Run npm start
2. Go to http://localhost:8000/edit

Expected result:
A web page opens

Observed result:
Server does a redirect but there is no response from the target location (e.g. http://localhost:8000/gbrghyywjo2n)

Console output:
```
❯ npm start

> Vizor@0.5.0 start /home/antti/projects/vizor
> node app.js

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
RethinkDB connected
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
OSC server at port: 8001
Channel server ready
EditorChannelServer ready
GET /edit 302 13.984 ms - 70
Potentially unhandled rejection [1] ReqlOpFailedError: Database `vizor` does not exist in:
r.table("editlog").filter(r.row("name").eq("gbrghyywjo2n")).limit(1).orderBy("id")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at ReqlOpFailedError.ReqlRuntimeError [as constructor] (/home/antti/projects/vizor/node_modules/rethinkdb/errors.js:72:13)
    at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (/home/antti/projects/vizor/node_modules/rethinkdb/errors.js:150:56)
    at new ReqlOpFailedError (/home/antti/projects/vizor/node_modules/rethinkdb/errors.js:161:52)
    at mkErr (/home/antti/projects/vizor/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/home/antti/projects/vizor/node_modules/rethinkdb/net.js:148:16)
    at TcpConnection.Connection._data (/home/antti/projects/vizor/node_modules/rethinkdb/net.js:118:12)
    at Socket.<anonymous> (/home/antti/projects/vizor/node_modules/rethinkdb/net.js:509:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by kschzt** [comment]
@apaatsio moi! please run:

```
$ node tools/setup.js
$ gulp
```
