### ISSUE TITLE
error when saving preset: chunks out of order

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#733]
if I insist enough times on saving a preset, I eventually get an error. console reads: 

GET /banana/presets/?_=1445458881873 200 4.542 ms - -
MongoError: exception: chunks out of order
    at Object.toError (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Volumes/data/Users/george/code/vizor/vizorcreate/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by fthr** [comment]
Saving presets (now saving "patches") seems to work correctly now.
